### ISSUE TITLE
Crash when trying to set value on UE 5.0.3

### ISSUE THREAD

**Issue by Osama-Gamal** [feixuwu/document#7]
I followed the same instructions to set value on realtime database and when I click on the button to set the value the engine crash with the value 

UnrealEditor_EasyFirebase!firebase::scheduler::Scheduler::Schedule()
UnrealEditor_EasyFirebase!firebase::database::internal::DatabaseReferenceInternal::SetValue()
UnrealEditor_EasyFirebase!firebase::database::DatabaseReference::SetValue()
UnrealEditor_EasyFirebase!UFirebaseDatabaseRef::SetValue() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\EasyFirebasePro\Source\EasyFirebase\Private\FirebaseDatabaseRef.cpp:200]
UnrealEditor_EasyFirebase!UFirebaseDatabaseRef::execSetValue() [d:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\EasyFirebasePro\Intermediate\Build\Win64\UnrealEditor\Inc\EasyFirebase\FirebaseDatabaseRef.gen.cpp:198]
UnrealEditor_CoreUObject

**Comment by feixuwu** [comment]
can u send me an example to reproduce it?
c++ is more difficult then blueprint, memory, thread all can cause problems.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Osama Gamal ***@***.***>
Sent: Tuesday, September 19, 2023 12:13:56 AM
To: feixuwu/document ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [feixuwu/document] Crash when trying to set value on UE 5.0.3 (Issue #7)


I followed the same instructions to set value on realtime database and when I click on the button to set the value the engine crash with the value

UnrealEditor_EasyFirebase!firebase::scheduler::Scheduler::Schedule()
UnrealEditor_EasyFirebase!firebase::database::internal::DatabaseReferenceInternal::SetValue()
UnrealEditor_EasyFirebase!firebase::database::DatabaseReference::SetValue()
UnrealEditor_EasyFirebase!UFirebaseDatabaseRef::SetValue() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\EasyFirebasePro\Source\EasyFirebase\Private\FirebaseDatabaseRef.cpp:200]
UnrealEditor_EasyFirebase!UFirebaseDatabaseRef::execSetValue() [d:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\EasyFirebasePro\Intermediate\Build\Win64\UnrealEditor\Inc\EasyFirebase\FirebaseDatabaseRef.gen.cpp:198]
UnrealEditor_CoreUObject

―

**Comment by feixuwu** [comment]
please disable android file server in project setting, it will fix the problem.

**Comment by Osama-Gamal** [comment]
It works now, Thank you.

**Comment by Osama-Gamal** [comment]
Fixed
